### ISSUE TITLE
点击完成任务会一直转圈，但数据会有记录，报错Cannot read property 'user_integral' of undefined

### ISSUE THREAD

**Issue by Https443** [LCM9902/Duck-Princess-Cultivation-Plan#20]
```
Unhandled promise rejection Error: cloud.callFunction:fail Error: errCode: -504002 functions execute fail | errMsg: Cannot read property 'user_integral' of undefined
TypeError: Cannot read property 'user_integral' of undefined
    at Object.exports.main (/var/user/updateUser/index.js:15:35)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) (callId: 1649936203495-0.3246559563964737) (trace: 19:36:43 start->19:36:43 system error (Error: errCode: -504002 functions execute fail | errMsg: Cannot read property 'user_integral' of undefined
TypeError: Cannot read property 'user_integral' of undefined
    at Object.exports.main (/var/user/updateUser/index.js:15:35)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)), abort)
    at C (http://127.0.0.1:19669/appservice/__dev__/WAService.js:2:658323)
    at http://127.0.0.1:19669/appservice/__dev__/WAService.js:2:684615
    at http://127.0.0.1:19669/appservice/__dev__/WAService.js:2:46812
    at n (http://127.0.0.1:19669/appservice/__dev__/WAService.js:2:23689)(env: macOS,mp,1.05.2203251; lib: 2.23.4)
e.exports @ VM14 WAService.js:2
ne @ VM14 WAService.js:2
(anonymous) @ VM14 WAService.js:2
e.exports @ VM14 WAService.js:2
(anonymous) @ VM14 WAService.js:2
(anonymous) @ VM13 asdebug.js:1
p @ VM13 asdebug.js:1
u @ VM14 WAService.js:2
(anonymous) @ VM14 WAService.js:2
(anonymous) @ VM14 WAService.js:2
setTimeout (async)
globalThis.setTimeout @ VM14 WAService.js:2
o @ VM13 asdebug.js:1
f.setImmediate @ VM13 asdebug.js:1
ie @ VM14 WAService.js:2
(anonymous) @ VM14 WAService.js:2
n @ VM14 WAService.js:2
Promise.then (async)
o @ VM14 WAService.js:2
e.exports @ VM14 WAService.js:2
re @ VM14 WAService.js:2
le @ VM14 WAService.js:2
(anonymous) @ VM14 WAService.js:2
success @ VM14 WAService.js:2
success @ VM14 WAService.js:2
u @ VM14 WAService.js:2
(anonymous) @ VM14 WAService.js:2
a @ VM14 WAService.js:2
(anonymous) @ VM14 WAService.js:2
Ti @ VM14 WAService.js:2
(anonymous) @ VM14 WAService.js:2
(anonymous) @ VM13 asdebug.js:1
C @ VM13 asdebug.js:1
(anonymous) @ VM13 asdebug.js:1
f @ VM13 asdebug.js:1
g @ VM13 asdebug.js:1
(anonymous) @ VM13 asdebug.js:1
_ws.onmessage @ VM13 asdebug.js:1
```

**Comment by fuujiro** [comment]
兄弟 你知道为啥吗
